// Copyright 2025 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef FLL_REGS_H
#define FLL_REGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - fll::status
#define FLL__STATUS__MULT_bm 0xffff
#define FLL__STATUS__MULT_bp 0
#define FLL__STATUS__MULT_bw 16
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t mult :16;
        uint32_t :16;
    } f;
    uint32_t w;
} fll__status_t;

// Reg - fll::config1
#define FLL__CONFIG1__MULT_bm 0xffff
#define FLL__CONFIG1__MULT_bp 0
#define FLL__CONFIG1__MULT_bw 16
#define FLL__CONFIG1__DCO_IN_CODE_bm 0x3ff0000
#define FLL__CONFIG1__DCO_IN_CODE_bp 16
#define FLL__CONFIG1__DCO_IN_CODE_bw 10
#define FLL__CONFIG1__DIV_bm 0x3c000000
#define FLL__CONFIG1__DIV_bp 26
#define FLL__CONFIG1__DIV_bw 4
#define FLL__CONFIG1__GATE_OUTPUT_bm 0x40000000
#define FLL__CONFIG1__GATE_OUTPUT_bp 30
#define FLL__CONFIG1__GATE_OUTPUT_bw 1
#define FLL__CONFIG1__OP_MODE_bm 0x80000000
#define FLL__CONFIG1__OP_MODE_bp 31
#define FLL__CONFIG1__OP_MODE_bw 1
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t mult :16;
        uint32_t dco_in_code :10;
        uint32_t div :4;
        uint32_t gate_output :1;
        uint32_t op_mode :1;
    } f;
    uint32_t w;
} fll__config1_t;

// Reg - fll::config2
#define FLL__CONFIG2__LOOP_GAIN_bm 0xf
#define FLL__CONFIG2__LOOP_GAIN_bp 0
#define FLL__CONFIG2__LOOP_GAIN_bw 4
#define FLL__CONFIG2__LOCK_CNT_LO_bm 0x3f0
#define FLL__CONFIG2__LOCK_CNT_LO_bp 4
#define FLL__CONFIG2__LOCK_CNT_LO_bw 6
#define FLL__CONFIG2__LOCK_CNT_HI_bm 0xfc00
#define FLL__CONFIG2__LOCK_CNT_HI_bp 10
#define FLL__CONFIG2__LOCK_CNT_HI_bw 6
#define FLL__CONFIG2__LOCK_TOL_bm 0xfff0000
#define FLL__CONFIG2__LOCK_TOL_bp 16
#define FLL__CONFIG2__LOCK_TOL_bw 12
#define FLL__CONFIG2__STA_CLK_SEL_bm 0x20000000
#define FLL__CONFIG2__STA_CLK_SEL_bp 29
#define FLL__CONFIG2__STA_CLK_SEL_bw 1
#define FLL__CONFIG2__OLWL_bm 0x40000000
#define FLL__CONFIG2__OLWL_bp 30
#define FLL__CONFIG2__OLWL_bw 1
#define FLL__CONFIG2__DITH_EN_bm 0x80000000
#define FLL__CONFIG2__DITH_EN_bp 31
#define FLL__CONFIG2__DITH_EN_bw 1
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t loop_gain :4;
        uint32_t lock_cnt_lo :6;
        uint32_t lock_cnt_hi :6;
        uint32_t lock_tol :12;
        uint32_t :1;
        uint32_t sta_clk_sel :1;
        uint32_t olwl :1;
        uint32_t dith_en :1;
    } f;
    uint32_t w;
} fll__config2_t;

// Reg - fll::integrator
#define FLL__INTEGRATOR__FRAC_PART_bm 0xfe00
#define FLL__INTEGRATOR__FRAC_PART_bp 9
#define FLL__INTEGRATOR__FRAC_PART_bw 7
#define FLL__INTEGRATOR__INT_PART_bm 0x3ff0000
#define FLL__INTEGRATOR__INT_PART_bp 16
#define FLL__INTEGRATOR__INT_PART_bw 10
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t :9;
        uint32_t frac_part :7;
        uint32_t int_part :10;
        uint32_t :6;
    } f;
    uint32_t w;
} fll__integrator_t;

// Addrmap - fll
typedef struct __attribute__ ((__packed__)) {
    fll__status_t status;
    fll__config1_t config1;
    fll__config2_t config2;
    fll__integrator_t integrator;
} fll_t;


static_assert(sizeof(fll_t) == 0x10, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* FLL_REGS_H */
